name: "Build & Release"

on:
  push:
    branches: [master]

jobs:
  development:
    name: 🎉 Convert Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          
      - name: run python code find file
        id: convert
        run: |
          output=$(python find.py)
          echo "ReleaseNumber=$output" >> $GITHUB_OUTPUT

      - name: Generate JSON
        uses: novaday-co/localization_action@1.0.0
        with:
          input_file: ${{ steps.convert.outputs.ReleaseNumber }}.xlsx
          generate_flutter: true
          generate_laravel: true
          generate_vue: true

      - name: Push To Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.json,*.arb'
          tag : ${{ steps.convert.outputs.ReleaseNumber }}+${{ github.run_number }}
          token : ${{ secrets.TOKEN }}
