name: "Build & Release"

on:
  push:
    branches: [master]

jobs:
  development:
    name: 🎉 Convert Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install compatible numpy and pandas
        run: |
            pip install "numpy<1.24" "pandas==1.5.3"

      - name: run python code find file
        id: convert
        run: |
          output=$(python find.py)
          echo "ReleaseNumber=$output" >> $GITHUB_OUTPUT

      - name: Generate JSON
        uses: novaday-co/localization_action@1.1.0
        with:
          input_file: ${{ steps.convert.outputs.ReleaseNumber }}.xlsx
          generate_flutter: true
          generate_laravel: true
          generate_vue: true

    - name: Push To Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.json,*.arb'
          tag: ${{ steps.convert.outputs.ReleaseNumber }}+${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
